// src/constants/skillList.js
// Single source of truth for all skill options.
// Import this in WorkerRegister, ClientDashboard, ClientJobPost, ClientJobManage
// instead of defining the array in each file.

const skillList = [
    'Painter',
    'Carpenter',
    'Plumber',
    'Electrician',
    'Mason / Bricklayer',
    'Welder',
    'Tiler',
    'Roofer',
    'Flooring Specialist',
    'Glass / Window Fitter',
    'Steel Fabricator',
    'AC Technician',
    'Refrigeration Technician',
    'Solar Panel Installer',
    'CCTV / Security Systems',
    'Lift / Elevator Technician',
    'Fire Safety Technician',
    'Generator Mechanic',
    'Interior Designer',
    'False Ceiling Specialist',
    'Wallpaper / Texture Artist',
    'Furniture Assembler',
    'Kitchen Cabinet Installer',
    'Modular Kitchen Expert',
    'Wardrobe Fitter',
    'Curtain / Blinds Installer',
    'Landscaping / Garden',
    'Waterproofing Specialist',
    'Pest Control',
    'Deep Cleaning / Housekeeping',
    'Sofa / Upholstery Cleaning',
    'Geyser / Water Heater Repair',
    'RO / Water Purifier Service',
    'Washing Machine Repair',
    'Microwave / Oven Repair',
    'TV / Electronics Repair',
    'Computer / Laptop Repair',
    'Mobile Phone Repair',
    'Inverter / Battery Service',
    'Packers & Movers',
    'Driver / Chauffeur',
    'Delivery / Courier',
    'Security Guard',
    'Handyman / General Helper',
    'Demolition / Debris Removal',
    'Excavation / Earth Work',
    'Construction Labour',
    'Scaffolding',
    'Civil Contractor',
    'Other',
];

export default skillList;